/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f401xc.h"
#include "STM_Config.h"
#include "STM_LCD.h"


int main(void)
{
	LCD_Init();
	LCD_PutCursor(0,0);
	LCD_Send_String("Created File");
	LCD_PutCursor(1,0);
	LCD_Send_String("Successfully");
	STM_DelayMS(5000);

    /* Loop forever */
	while(1)
	{

	}
}
